import { useEffect, useState } from 'react'
import { fetchAllPages, responseList, apiRequest } from '../../api/client.js'
import { Erro } from '../../components/Erro.jsx'
import { CabecalhoPagina } from '../../components/CabecalhoPagina.jsx'
import { Carregando } from '../../components/Carregando.jsx'
import { EstadoVazio } from '../../components/EstadoVazio.jsx'
import { resolveRelatedName } from '../../utils/appointments.js'

export function Avaliacoes() {
  const [reviews, setReviews] = useState([]); const [resources, setResources] = useState([]); const [services, setServices] = useState([]); const [resourceId, setResourceId] = useState(''); const [rating, setRating] = useState(''); const [next, setNext] = useState(false); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async (append = false) => { try { setLoading(true); setError(''); const query = `/avaliacoes/?${resourceId ? `recurso=${resourceId}&` : ''}${rating ? `nota=${rating}&` : ''}page=${append ? page + 1 : 1}`; const [response, resourceList, serviceList] = await Promise.all([apiRequest(query), resources.length ? Promise.resolve(resources) : fetchAllPages('/recursos/'), services.length ? Promise.resolve(services) : fetchAllPages('/servicos/')]); const list = responseList(response); setReviews((current) => append ? [...current, ...list] : list); setNext(Boolean(response?.next)); setPage(append ? page + 1 : 1); if (!resources.length) setResources(resourceList); if (!services.length) setServices(serviceList) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [resourceId, rating])
  return <section className="page-block"><CabecalhoPagina title="Avaliações" subtitle="Acompanhe a satisfação dos pacientes." backLabel="Voltar para administração" backTo="/admin" /><div className="date-row"><label>Psicólogo<select value={resourceId} onChange={(event) => setResourceId(event.target.value)}><option value="">Todos</option>{resources.map((resource) => <option value={resource.id} key={resource.id}>{resource.nome}</option>)}</select></label><label>Nota<select value={rating} onChange={(event) => setRating(event.target.value)}><option value="">Todas</option>{[1, 2, 3, 4, 5].map((value) => <option value={value} key={value}>{value}</option>)}</select></label></div>{loading ? <Carregando message="Carregando avaliações" /> : null}{error ? <><Erro type="danger" message={error} /><button className="button-secondary" onClick={() => load()}>Tentar de novo</button></> : null}<div className="card section-card">{!loading && !error && !reviews.length ? <EstadoVazio title="Ainda sem avaliações" description="Nenhuma avaliação corresponde aos filtros." /> : <div className="list-stack">{reviews.map((item) => { const resourceName = resolveRelatedName(item.recurso, resources, item.recurso_nome || item.psicologo_nome); const serviceName = resolveRelatedName(item.servico, services, item.servico_nome || item.nome_servico); return <div className="list-item" key={item.id}><div><strong>{item.nota}/5 • {resourceName || 'Profissional'}</strong><p>{item.comentario || 'Sem comentário.'}</p><p><strong>Paciente:</strong> {item.cliente?.nome || item.cliente_nome || item.paciente?.nome || 'Não informado'}</p><p><strong>Serviço:</strong> {serviceName || 'Não informado'}</p></div></div> })}{next ? <button type="button" className="button-secondary" disabled={loading} onClick={() => load(true)}>{loading ? 'Carregando...' : 'Carregar mais'}</button> : null}</div>}</div></section>
}

export default Avaliacoes
